### ISSUE TITLE
分享 doc、md 格式

### ISSUE THREAD

**Issue by Ma3k4H3d** [Micropoor/Micro8#1]
Word 版：https://github.com/micro8/Micro8-doc
MarkDown 版：https://github.com/micro8/Gitbook

**Comment by Micropoor** [comment]
> Word版：[https](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc)：[//github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc)
> MarkDown版：[https](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md)：[//github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md)

非常感谢

**Comment by maskhed** [comment]
> > Word版：[https](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc)：[//github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc)
> > MarkDown版：[https](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md)：[//github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md)
> 
> 非常感谢

弟与亮哥保持同步

**Comment by trexguo** [comment]
建议本仓库尽早全部转为md格式，好处有：

1. 方便编译生在线站点，比如使用gitbook
2. 方便后期转成其他格式，如pdf
3. 方便读者针对某行进行讨论、提问
4. 方便读者进行校阅，不断完善
5. 有变更履历和贡献履历，让作者和读者清楚文章的更新。

@Micropoor @maskhed

**Comment by yyt6801** [comment]
膜拜，一天涨到近1.5K的star量，作者辛苦了。在此也提一些愚见：
1）内容都很良心，但门槛较高，作为一名混了几年的信安僧，好多东西仍初次接触；
2）确实如前几位所说，格式问题，有些许混乱，建议使用gitbook；
3）文档里好多链接都已失效；
4）

**Comment by Micropoor** [comment]
> 建议本仓库尽早全部转为md格式，好处有：
> 
> 1. 方便编译生在线站点，比如使用gitbook
> 2. 方便后期转成其他格式，如pdf
> 3. 方便读者针对某行进行讨论、提问
> 4. 方便读者进行校阅，不断完善
> 5. 有变更履历和贡献履历，一目了然
> 
> @Micropoor @maskhed

感谢 由于目前维护只有我一人，故发到github上，大家提出建议，现在主更200课时后，我修正200课。愿大家共同维护

**Comment by Micropoor** [comment]
> 4）

非常感谢建议，一定会越来越完善，越来越符合无论从阅读，还是学习亦或是保存都将会完善。

**Comment by memory125** [comment]
非常感谢整理&分享！

**Comment by Micropoor** [comment]
> 膜拜，一天涨到近1.5K的star量，作者辛苦了。在此也提一些愚见：
> 1）内容都很良心，但门槛较高，作为一名混了几年的信安僧，好多东西仍初次接触；
> 2）确实如前几位所说，格式问题，有些许混乱，建议使用gitbook；
> 3）文档里好多链接都已失效；
> 4）

https://micro8.gitbook.io/micro8/

**Comment by maskhed** [comment]
> > Word版：[https](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc)：[//github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-doc)
> > MarkDown版：[https](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md)：[//github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md](https://github.com/maskhed/Papers/tree/master/Micropoor/Micropoor-md)
> 
> 非常感谢

最新版已更新至 https://github.com/micro8，原链接将关闭。
