### ISSUE TITLE
小建议：每课开头写一下为什么用这种攻击方式，有什么优点，可以解决什么问题

### ISSUE THREAD

**Issue by hjchjcjh** [Micropoor/Micro8#18]
小建议：每课开头写一下为什么用这种攻击方式，有什么优点，可以解决什么问题

**Comment by Micropoor** [comment]
> 小建议：每课开头写一下为什么用这种攻击方式，有什么优点，可以解决什么问题

未来的课时中，会增改该建议，感谢
