### ISSUE TITLE
老师好，新学员报道

### ISSUE THREAD

**Issue by ericnts** [Micropoor/Micro8#2]
readme 倒数第四个汉字写错喽

**Comment by ericnts** [comment]
第一章
![image](https://user-images.githubusercontent.com/43471419/53006272-db7e1c00-346f-11e9-9dd1-cbddb338a5ba.png)

**Comment by Micropoor** [comment]
> 第一章
> ![图片](https://user-images.githubusercontent.com/43471419/53006272-db7e1c00-346f-11e9-9dd1-cbddb338a5ba.png)

非常感谢。

**Comment by Micropoor** [comment]
> readme 倒数第四个汉字写错喽

更改为：私有所惘，意为：不去分享，私自藏有，定会迷惘。

**Comment by CLXgithub** [comment]
我的网速加载不出来PDF  233333

**Comment by EvilPulsar** [comment]
感谢感谢！

**Comment by ericnts** [comment]
看了几章   感觉快要放弃了  
不是说好零基础入门的， 为啥我一个三年编程经验的人来看，还是看不懂。
感觉写的不像是教程了，更像是工具书，没点这方面基础的是看不出所以然的

**Comment by chriiess** [comment]
感谢您无私的分享

**Comment by LiuCong159520** [comment]
完全看不懂啊,看来这适合专门做安全防御的人看

**Comment by Arsense** [comment]
感谢分享
