### ISSUE TITLE
Any English Description might help..

### ISSUE THREAD

**Issue by aungthurhahein** [Micropoor/Micro8#3]

**Comment by CaledoniaProject** [comment]
It's something like `personal notes about my pentesting / red teaming experiments`

**Comment by vamzii** [comment]
can some one translate this to english pls?

**Comment by adolphor** [comment]
> can some one translate this to english pls?

That will be a huge project.

**Comment by PACEJJ27** [comment]
> can some one translate this to english pls?

Maybe you should learn chinese
