### ISSUE TITLE
建议：按书的章节进行归类

### ISSUE THREAD

**Issue by jinyahuan** [Micropoor/Micro8#4]
方便阅读，也方便以后整理成完整的书籍目录。
如：
|- 前言
|- 第一章_生
--|- 第一节课.pdf
--|- 第n节课.pdf
|- 第二章_老
|- ...

**Comment by Micropoor** [comment]
> 方便阅读，也方便以后整理成完整的书籍目录。
> 如：
> |- 前言
> |- 第一章_生
> --|- 第一节课.pdf
> --|- 第n节课.pdf
> |- 第二章_老
> |- ...

后续会修正

**Comment by CaledoniaProject** [comment]
你不如搞个 gitbook，wiki 里有目录结构却没有链接到PDF，鸡肋

**Comment by CaledoniaProject** [comment]
最后补一句，gitbook 可以直接生成PDF，epub，就不用你搞成单个PDF了。

**Comment by Micropoor** [comment]
> 你不如搞个 gitbook，wiki 里有目录结构却没有链接到PDF，鸡肋。
> 
> Gitbook 都是 markdown 的，出来之后的格式类似这样: https://rasp.baidu.com/doc/ https://ired.team/

非常感谢您的建议，后期一定修正为gitbook

**Comment by jinyahuan** [comment]
> 最后补一句，gitbook 可以直接生成PDF，epub，就不用你搞成单个PDF了。

确实 gitbook 更方便阅读，也更方便别人提交合并

**Comment by jinyahuan** [comment]
> > 方便阅读，也方便以后整理成完整的书籍目录。
> > 如：
> > |- 前言
> > |- 第一章_生
> > --|- 第一节课.pdf
> > --|- 第n节课.pdf
> > |- 第二章_老
> > |- ...
> 
> 后续会修正，请看wiki，wiki中有目录结构

嗯 现在就是参考wiki 搜内容 --

**Comment by VectorLu** [comment]
> > 你不如搞个 gitbook，wiki 里有目录结构却没有链接到PDF，鸡肋。
> > Gitbook 都是 markdown 的，出来之后的格式类似这样: https://rasp.baidu.com/doc/ https://ired.team/
> 
> 非常感谢您的建议，后期一定修正为gitbook

十分建议您将章节按类似Chapeter 001-Chapter 999这样的阿拉伯数字排序，这样文件能按字母序整齐排列，无论是读者按顺序阅读，还是您自己查找修改都会更加方便。

**Comment by chendayang** [comment]
楼主建议您文件名稍微改一下，如：
“Asp代码审计--项目实战2（第四课）.pdf” =>“1.2-Asp代码审计--项目实战.md”

章节用数字，放在前面，方便排序，pdf楼上的诸位讲过了，就不提了，相信不久楼主会改成markdown格式的。

**Comment by iclodq** [comment]
非常感谢作者的分享!! 加油哟!!

**Comment by Micropoor** [comment]
> > 最后补一句，gitbook 可以直接生成PDF，epub，就不用你搞成单个PDF了。
> 
> 确实 gitbook 更方便阅读，也更方便别人提交合并

https://github.com/maskhed/Micro8-Gitbook/

**Comment by Micropoor** [comment]
https://github.com/maskhed/Micro8-Gitbook/  地址
