### ISSUE TITLE
还是有很多关键词看不懂，渗透测试的大体流程也不清楚，可以写一下学习该教程需要哪些基础知识吗？

### ISSUE THREAD

**Issue by MoonandMind** [Micropoor/Micro8#41]

**Comment by owen800q** [comment]
Before reading those materials, I think you should have strong foundation in unix network programming and network protocols
I highly recommend the book computer networking, a top down approach, all you need to know about networking are included in this book..

learn more advanced Linux shell scripting and 8086 assembly language

**Comment by owen800q** [comment]
Roadmap
Programming & Coding
C, C++, C# and Java
Python, and poweshell scripting 
Assembly language 
Regular Expression (regex) skills
Linux Bash shell scripting
Networks

System/network configuration
TCP/IP, computer networking, routing and switching
Network protocols and packet analysis 
Firewall and intrusion detection/prevention protocols
Packet Shaper, Load Balancer and Proxy Server knowledge
VPNs

**Comment by delovt** [comment]
渗透测试是一个大门类, 而且特别吃经验, 前端后端主机网络社工协议编程内核设计模式等一大堆东西, 对于所谓的 "基础知识", 想必无论是前辈们的书/文章都已经说得很清楚了, 先学编程, 如果你来不及想要去体验一把作为一个 hacker 的感觉, 玩 CTF 去吧, 目标可见, 有解题思路, 完善的培训机制, 跟打游戏一样了.

**Comment by xichen-li** [comment]
牛牛牛

**Comment by MoonandMind** [comment]
@owen800q @delovt 感谢回复 (*￣︶￣)
