### ISSUE TITLE
如何从远程3389下载shift后门样本到本地分析？

### ISSUE THREAD

**Issue by private14** [Micropoor/Micro8#44]
如何从远程3389下载shift后门样本到本地分析？

**Comment by delovt** [comment]
所谓的 shift 后门不过是替换掉了对应的文件, 起到可以在登录页面连按 5 下弹出一个 cmd 或者是激活自定义工具来以此攻陷系统的目的. 这个"后门"的定义主要还是看你面对的弹出来的工具, 如果只是把 cmd 覆盖过去, 那不过就是一个每个系统都有的 cmd, 你的 windows 电脑上也有. 如果说是别人自己写的东西, 或者说如果你不是系统管理员, 请参照 "中华人民共和国网络安全法" 第三章第二十七条和第六章第六十三条, 当然如果你是系统管理员的话, 直接复制对应目录下的文件出来就行, 想怎么分析都可以, 希望能看到你的分析文章. hack for fun, lol

**Comment by C0der1iu** [comment]
那一篇文章里面写的是 利用DHCP服务的loadfile漏洞，这个需要前提的。

**Comment by private14** [comment]
谢谢
