### ISSUE TITLE
感谢分享

### ISSUE THREAD

**Issue by huangjianke** [Micropoor/Micro8#8]
开源有你真好

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by Micropoor** [comment]
> 开源有你真好
> 
> **来自GitHub的小程序客户端：**
> 
> ![图片](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

您客气，愿某天您也加入知识的免费，共享，开源，自由的传递中。
