### ISSUE TITLE
思路与具体实现

### ISSUE THREAD

**Issue by yckyos261** [Micropoor/Micro8#9]
```
攻击思路为：16进制读取shift后门，并unhex本地还原exe，得到样本2，本地分析该样
本，从而不留痕迹得得到攻击者服务器
```
如果方便的话类似这样的思路能否附上稍微详细的具体实现。如16进制读取shift后门怎么读取的。用什么方式方法？
感谢。

**Comment by evil7** [comment]
@yckyos261 这个只能视情况而定吧。要举例的话，如果有Shell环境可以用Powershell读文件，ReadAllBytes然后Convert为HEX字符串返回；如果旁路方式获取文件(MySQL)直接hex(readfile('C:\\xxx.exe'))就行了；或是SSRF用php://伪协议转Base64或者HEX读出来，尝试file:///协议直接下载后门也行。
过程思路是重点，具象手法因地制宜。
